language: ruby
cache: bundler
rvm:
  - 2.2.7
  - 2.3.4
  - 2.4.1
  - jruby
gemfile:
  - gemfiles/mongoid_5.2.gemfile
  - gemfiles/mongoid_6.0.gemfile
  - gemfiles/mongoid_6.1.gemfile
  - gemfiles/mongoid_6.2.gemfile
bundler_args: "--jobs=3 --retry=3"
script:
  - bundle exec rubocop && bundle exec rake
